{
 "title": "Artrade manager dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Good part counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsi_ld_job_202200045_job\nWHERE\n  attrname = 'GoodPartCounter'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Input storage alert",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsi_ld_storage_trayloaderstorage1_storage\nWHERE\n  attrname = 'Counter' and\n  recvtimets = (select recvtimets from default_service.urn_ngsi_ld_storage_trayloaderstorage1_storage order by recvtimets desc limit 1)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsi_ld_oee_injectionmoulding1_oee\nWHERE\n  attrname = 'OEE' and\n  attrvalue != 'null'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsi_ld_oee_injectionmoulding1_oee\nWHERE\n  attrname = 'Availability' and\n  attrvalue != 'null'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsi_ld_oee_injectionmoulding1_oee\nWHERE\n  attrname = 'Performance' and\n  attrvalue != 'null'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsi_ld_oee_injectionmoulding1_oee\nWHERE\n  attrname = 'Quality' and\n  attrvalue != 'null'\nORDER BY 1\n"
    }
   ]
  }
 ]
}